### ISSUE TITLE
Parse with saving new line

### ISSUE THREAD

**Issue by MaslovAnton** [mak-it/saxlsx#12]
Hello! How can I parse xlxs file with text includes new line simbols?

**Comment by ebeigarts** [comment]
Hi, can you give an example file?

**Comment by MaslovAnton** [comment]
[test.xlsx](https://github.com/mak-it/saxlsx/files/3310088/test.xlsx)

**Comment by MaslovAnton** [comment]
`    Saxlsx::Workbook.open file do |w|
      w.sheets.each do |s|
        s.rows.each do |r|
          p r -> ["Test Test1 Test3"]
        end
      end
    end`

**Comment by MaslovAnton** [comment]
`Saxlsx::Workbook.open file do |w|
  w.sheets.each do |s|
        s.rows.each do |r|
          p r
        end
      end
    end`

**Comment by MaslovAnton** [comment]
`Saxlsx::Workbook.open file do |w|`
`   w.sheets.each do |s|`
`        s.rows.each do |r|`
`          p r -> ["Test Test1 Test3"]`
`        end`
`      end`
`    end`

**Comment by ebeigarts** [comment]
@MaslovAnton I have released v1.9.0 that should support multiline values
